# Konfigurasi Aset untuk Smart Money Concept Analyzer
# --------------------------------------------------
# Format:
#   assets:
#     - symbol: <simbol aset>
#       type: <jenis aset>
#       exchange: <bursa>
#       parameters: <parameter khusus aset>
#       timeframes: <timeframe yang dianalisis>
#
# Daftar timeframe yang didukung: 
#   [1m, 5m, 15m, 30m, 1h, 4h, 1d, 1w]

# Parameter global untuk semua aset
global_parameters:
  min_candles: 50
  volume_multiplier: 2.5
  fvg_min_strength: 0.5
  liquidity_lookback: 20
  swing_window: 5
  supported_timeframes:  # Daftar timeframe yang valid
    - 1m
    - 5m
    - 15m
    - 30m
    - 1h
    - 4h
    - 1d
    - 1w

# Kelompok Aset Kripto
crypto_assets:
  - symbol: BTCUSDT
    exchange: Binance
    parameters:
      min_candles: 100  # Lebih banyak candle untuk volatilitas tinggi
      volume_multiplier: 2.0
    timeframes:
      - 15m
      - 1h
      - 4h
      - 1d

  - symbol: ETHUSDT
    exchange: Binance
    parameters:
      fvg_min_strength: 0.4  # Lebih sensitif untuk ETH
    timeframes:
      - 15m
      - 1h
      - 4h

  - symbol: SOLUSDT
    exchange: Binance
    timeframes:
      - 5m
      - 15m
      - 1h

# Kelompok Pasangan Forex
forex_assets:
  - symbol: EURUSD
    exchange: OANDA
    parameters:
      min_candles: 200  # Analisis lebih panjang untuk forex
      liquidity_lookback: 50
    timeframes:
      - 30m
      - 1h
      - 4h
      - 1d

  - symbol: GBPJPY
    exchange: OANDA
    parameters:
      volume_multiplier: 3.0  # Volume lebih rendah di forex
      swing_window: 7
    timeframes:
      - 1h
      - 4h

# Kelompok Saham
stock_assets:
  - symbol: AAPL
    exchange: NASDAQ
    parameters:
      min_candles: 75
      fvg_min_strength: 0.6
    timeframes:
      - 1h
      - 4h
      - 1d

  - symbol: TSLA
    exchange: NASDAQ
    parameters:
      volume_multiplier: 3.0
      swing_window: 4
    timeframes:
      - 15m
      - 1h
      - 4h

# Kelompok Indeks
index_assets:
  - symbol: SPX500
    exchange: NYSE
    parameters:
      min_candles: 200
      liquidity_lookback: 40
    timeframes:
      - 4h
      - 1d
      - 1w

# Kelompok Komoditas
commodity_assets:
  - symbol: XAUUSD
    exchange: COMEX
    parameters:
      fvg_min_strength: 0.3  # Emas sering memiliki FVG lebih kecil
      volume_multiplier: 1.8
    timeframes:
      - 1h
      - 4h
      - 1d

# Template untuk menambahkan aset baru:
#  - symbol: 
#    exchange: 
#    parameters:
#      min_candles: 
#      volume_multiplier: 
#      fvg_min_strength: 
#      liquidity_lookback: 
#      swing_window: 
#    timeframes:
#      - 
#      -